routes/web.php
Route::post('/restaurant/update', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'updateRestaurant'])->name('updateRestaurant');

Route::get('/restaurant/waitting', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'afterRegistrationView'])->name('afterRegistrationView');

/*
=============================================================================================================
Order and checkout route
=============================================================================================================
*/

// Order route
Route::post('/get/food/data', [App\Http\Controllers\FoodController::class, 'getFoodData'])->name('createOrder');

Route::get('/create/order', [App\Http\Controllers\OrderController::class, 'index'])->name('createOrder');

Route::post('/create/order/notAuth', [App\Http\Controllers\OrderController::class, 'notAuthIndex'])->name('createOrderNotAuth');

Route::post('/store/order', [App\Http\Controllers\OrderController::class, 'store'])->name('storeOrder');

// Payment form
Route::post('/checkout', [App\Http\Controllers\checkoutController::class, 'index'])->name('checkout');

Route::post('/changelocale', [\App\Http\Controllers\TranslationController::class, 'changeLocale'])->name('changelocale');


// Route::get('/restaurant', function () {
//     return view('frontOffice.pages.restaurantSingle');
// })->name('restaurant.show');

// Customer login page
// Route::get('/customer/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'showLoginForm'])->name('customer.login');

// Route::post('/customer/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'guard'])->name('customer.store');
// Route::get('/customer/login', function () {
//     return view('customer.Auth.login');
// })->name('login');


// Auth::routes(['verify' => true]);

Route::get('/domli-admin', [App\Http\Controllers\HomeController::class, 'index'])->middleware('verified');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware('verified');

// Route::get('/home', 'HomeController@index')->middleware('verified');


/*
============================================================================================
Customer route
============================================================================================
*/
Route::get('/partenaire/restaurants', function () {
    return view('customer.pages.pagerestau');
});


Route::get('/otp', function () {
    return view('frontOffice.pages.otpPhonePage');
})->name('otp');

Route::get('/about', function () {
    return view('frontOffice.pages.about');
})->name('aboutUs');

Route::get('/page/contact', function () {
    return view('frontOffice.pages.contact');
})->name('contactUs');

// Route::get('/order', function () {
//     return view('frontOffice.pages.orderDetail');
// })->name('orderDetail');
// /*
// ============================================================================================
// delivery route
// ============================================================================================
// */
// //

Route::get('/delivery/home', function () {
    return view('customer.homePage.test');
});

Route::get('/delivery/chooseMoveMeans', function () {
    return view('deliverer.pages.chooseMoveMeans');
})->name('chooseMoveMeans');

Route::get('/delivery/lastRegisterStep', function () {
    return view('deliverer.pages.lastRegisterStep');
})->name('lastRegister');

Route::get('/deliverer/profileAuth', function () {
    return view('deliverer.pages.profileAuth');
    // return view('frontOffice.delivery.pages.profileAuth');
})->name('profileAuth');

Route::get('/delivery/offers', function () {
    return view('deliverer.pages.offerDetail');
})->name('offers');

Route::get('/delivery/otp', function () {
    return view('deliverer.pages.otpPhonePage');
})->name('deliveryOtpPage');

Route::get('/delivery/offer', function () {
    return view('deliverer.pages.offerDetail');
})->name('deliveryOffer');


Route::get('/customer/verify/{token}', [App\Http\Controllers\CustomerAuth\RegisterController::class, 'verifyCustomer'])->name('verifyCusomer');
Route::get('/delivery/verify/{token}', [App\Http\Controllers\DelivererAuth\RegisterController::class, 'verifyDeliverer'])->name('verifyDeliverer');

Route::get('/domli/congratulate', function () {
    return view('customer.pages.congratulate');
})->name('congratulate');


Route::get('/domli/congratulate/delivery', function () {
    return view('deliverer.pages.congratulate');
})->name('congratulateDeliverer');

// Email note verified page
// Route::get('/customer/waitpage', function () {
//     return view('customer.pages.waitpage');
// });


// Cart route

route::get('/food/detail/{uuid}', [App\Http\Controllers\CartController::class, 'foodOrderDetail'])->name('foodOrderDetail');

route::post('/add/food/', [App\Http\Controllers\CartController::class, 'store'])->name('cartStore');
route::post('/add/discount/', [App\Http\Controllers\CartController::class, 'addDiscount'])->name('addDiscount');

route::get('/cart/destroy', [App\Http\Controllers\CartController::class, 'destroy'])->name('emptyCart');

Route::group(['prefix' => 'deliverer'], function () {

    Route::get('/login', [App\Http\Controllers\DelivererAuth\LoginController::class, 'index'])->name('delivererLogin');

    Route::post('/login', [App\Http\Controllers\DelivererAuth\LoginController::class, 'login'])->name('delivery_login_post');

    Route::post('/logout', [App\Http\Controllers\DelivererAuth\LoginController::class, 'logout'])->name('delivery_logout');

    Route::get('/register', [App\Http\Controllers\DelivererAuth\RegisterController::class, 'showRegistrationForm'])->name('delivery_register_get');

    Route::post(
        '/register',
        [App\Http\Controllers\DelivererAuth\RegisterController::class, 'register']
    )->name('delivery_register_post');

    Route::post('/password/email', [App\Http\Controllers\DelivererAuth\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.request');

    Route::post('/password/reset', [App\Http\Controllers\DelivererAuth\ResetPasswordController::class, 'reset'])->name('password.email');

    Route::get('/password/reset', [App\Http\Controllers\DelivererAuth\ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.reset');

    Route::get('/password/reset/{token}', [App\Http\Controllers\DelivererAuth\ResetPasswordController::class, 'showResetForm']);
});


// OAuth Routes
Route::get('/auth/{provider}', [App\Http\Controllers\CustomerAuth\LoginController::class, 'redirectToProvider']);

Route::get('/auth/{provider}/callback', [App\Http\Controllers\CustomerAuth\LoginController::class, 'handleProviderCallback']);

Route::post('/search/restaurants', [App\Http\Controllers\RestaurantFrontController::class, 'searchRestaurant']);
Route::post('/search/foods', [App\Http\Controllers\RestaurantFrontController::class, 'searchFood']);

Route::get('policy/politic', function () {
    return view('customer.home');
});

// Route::get('/backOffice/restaurants', [App\Http\Controllers\RestaurantsController::class, 'index'])->middleware('auth');


// Route::get('/waitpage', function () {
//     return view('customer.pages.waitpage');
// })->name('wait');


Route::resource('vehicles', \App\Http\Controllers\VehicleController::class);

Route::resource('deliveryAvailaibities', \App\Http\Controllers\DeliveryAvailaibityController::class);

Route::resource('jobs', \App\Http\Controllers\JobController::class);

Route::resource('jobHistoriques', \App\Http\Controllers\JobHistoriqueController::class);

Route::resource('agentConnexions', \App\Http\Controllers\AgentConnexionController::class);

Route::resource('orderAssignements', \App\Http\Controllers\OrderAssignementController::class);

Route::resource('restaurantPayments', \App\Http\Controllers\RestaurantPaymentController::class);

Route::resource('deliveryPayments', \App\Http\Controllers\DeliveryPaymentController::class);

Route::resource('restaurantComptes', \App\Http\Controllers\RestaurantCompteController::class);

Route::resource('deliveryComptes', \App\Http\Controllers\DeliveryCompteController::class);

Route::resource('deliveryPaymentHistoriques', \App\Http\Controllers\DeliveryPaymentHistoriqueController::class);

Route::resource('restaurantPaymentHistoriques', \App\Http\Controllers\RestaurantPaymentHistoriqueController::class);
Route::get('/restaurant/{restaurant_id}/restaurantPaymentHistoriques', [\App\Http\Controllers\RestaurantPaymentHistoriqueController::class, 'restaurant'])->name('restaurantPaymentHistoriquesAdmin');

Route::resource('requestRestaurantPayments', \App\Http\Controllers\RequestRestaurantPaymentController::class);
Route::get('/restaurant/{restaurant_id}/requestRestaurantPayments', [\App\Http\Controllers\RequestRestaurantPaymentController::class, 'restaurant'])->name('requestRestaurantPaymentsAdmin');

Route::resource('requestDeliveryPayments', \App\Http\Controllers\RequestDeliveryPaymentController::class);

app/Models/RestaurantPayment.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class RestaurantPayment
 * @package App\Models
 * @version February 28, 2021, 7:46 pm UTC
 *
 * @property integer $restaurant_id
 * @property number $amount
 * @property boolean $is_paid
 * @property string $paid_date
 */
class RestaurantPayment extends Model
{
    use SoftDeletes;

    public $table = 'restaurant_payments';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'restaurant_id',
        'amount',
        'is_paid',
        'paid_date'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'restaurant_id' => 'integer',
        'amount' => 'double',
        'is_paid' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/RestaurantPaymentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRestaurantPaymentRequest;
use App\Http\Requests\UpdateRestaurantPaymentRequest;
use App\Repositories\RestaurantPaymentRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class RestaurantPaymentController extends AppBaseController
{
    /** @var  RestaurantPaymentRepository */
    private $restaurantPaymentRepository;

    public function __construct(RestaurantPaymentRepository $restaurantPaymentRepo)
    {
        $this->restaurantPaymentRepository = $restaurantPaymentRepo;
    }

    /**
     * Display a listing of the RestaurantPayment.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $restaurantPayments = $this->restaurantPaymentRepository->all();

        return view('restaurant_payments.index')
            ->with('restaurantPayments', $restaurantPayments);
    }

    /**
     * Show the form for creating a new RestaurantPayment.
     *
     * @return Response
     */
    public function create()
    {
        return view('restaurant_payments.create');
    }

    /**
     * Store a newly created RestaurantPayment in storage.
     *
     * @param CreateRestaurantPaymentRequest $request
     *
     * @return Response
     */
    public function store(CreateRestaurantPaymentRequest $request)
    {
        $input = $request->all();

        $restaurantPayment = $this->restaurantPaymentRepository->create($input);

        Flash::success('Restaurant Payment saved successfully.');

        return redirect(route('restaurantPayments.index'));
    }

    /**
     * Display the specified RestaurantPayment.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $restaurantPayment = $this->restaurantPaymentRepository->find($id);

        if (empty($restaurantPayment)) {
            Flash::error('Restaurant Payment not found');

            return redirect(route('restaurantPayments.index'));
        }

        return view('restaurant_payments.show')->with('restaurantPayment', $restaurantPayment);
    }

    /**
     * Show the form for editing the specified RestaurantPayment.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $restaurantPayment = $this->restaurantPaymentRepository->find($id);

        if (empty($restaurantPayment)) {
            Flash::error('Restaurant Payment not found');

            return redirect(route('restaurantPayments.index'));
        }

        return view('restaurant_payments.edit')->with('restaurantPayment', $restaurantPayment);
    }

    /**
     * Update the specified RestaurantPayment in storage.
     *
     * @param int $id
     * @param UpdateRestaurantPaymentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRestaurantPaymentRequest $request)
    {
        $restaurantPayment = $this->restaurantPaymentRepository->find($id);

        if (empty($restaurantPayment)) {
            Flash::error('Restaurant Payment not found');

            return redirect(route('restaurantPayments.index'));
        }

        $restaurantPayment = $this->restaurantPaymentRepository->update($request->all(), $id);

        Flash::success('Restaurant Payment updated successfully.');

        return redirect(route('restaurantPayments.index'));
    }

    /**
     * Remove the specified RestaurantPayment from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $restaurantPayment = $this->restaurantPaymentRepository->find($id);

        if (empty($restaurantPayment)) {
            Flash::error('Restaurant Payment not found');

            return redirect(route('restaurantPayments.index'));
        }

        $this->restaurantPaymentRepository->delete($id);

        Flash::success('Restaurant Payment deleted successfully.');

        return redirect(route('restaurantPayments.index'));
    }
}

resources/views/restaurant_payments/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('restaurantPayments.index') !!}">Restaurant Payment</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Restaurant Payment</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'restaurantPayments.store']) !!}

                                   @include('restaurant_payments.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/restaurant_payments/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('restaurantPayments.index') !!}">Restaurant Payment</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Restaurant Payment</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($restaurantPayment, ['route' => ['restaurantPayments.update', $restaurantPayment->id], 'method' => 'patch']) !!}

                              @include('restaurant_payments.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/restaurant_payments/fields.blade.php
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('restaurantPayments.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/restaurant_payments/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Restaurant Payments</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             RestaurantPayments
                             <a class="pull-right" href="{{ route('restaurantPayments.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('restaurant_payments.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/restaurant_payments/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('restaurantPayments.index') }}">Restaurant Payment</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('restaurantPayments.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('restaurant_payments.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/restaurant_payments/show_fields.blade.php
<!-- Restaurant Id Field -->
<div class="form-group">
    {!! Form::label('restaurant_id', 'Restaurant Id:') !!}
    <p>{{ $restaurantPayment->restaurant_id }}</p>
</div>

<!-- Amount Field -->
<div class="form-group">
    {!! Form::label('amount', 'Amount:') !!}
    <p>{{ $restaurantPayment->amount }}</p>
</div>

<!-- Is Paid Field -->
<div class="form-group">
    {!! Form::label('is_paid', 'Is Paid:') !!}
    <p>{{ $restaurantPayment->is_paid }}</p>
</div>

<!-- Paid Date Field -->
<div class="form-group">
    {!! Form::label('paid_date', 'Paid Date:') !!}
    <p>{{ $restaurantPayment->paid_date }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $restaurantPayment->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $restaurantPayment->updated_at }}</p>
</div>

resources/views/restaurant_payments/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="restaurantPayments-table">
        <thead>
            <tr>
                <th>Restaurant Id</th>
        <th>Amount</th>
        <th>Is Paid</th>
        <th>Paid Date</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($restaurantPayments as $restaurantPayment)
            <tr>
                <td>{{ $restaurantPayment->restaurant_id }}</td>
            <td>{{ $restaurantPayment->amount }}</td>
            <td>{{ $restaurantPayment->is_paid }}</td>
            <td>{{ $restaurantPayment->paid_date }}</td>
                <td>
                    {!! Form::open(['route' => ['restaurantPayments.destroy', $restaurantPayment->id]]) !!}
                    @method('DELETE')
                    <div class='btn-group'>
                        <a href="{{ route('restaurantPayments.show', [$restaurantPayment->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('restaurantPayments.edit', [$restaurantPayment->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>