routes/web.php
Route::get('/restaurants/categorie', [App\Http\Controllers\RestaurantFrontController::class, 'showCategorie'])->name('searchRestaurantsCategorie');

Route::get('page/restaurant/{uuid}', [RestaurantFrontController::class, 'show'])->name('restaurant');

Route::get('page/restaurants/categories', [RestaurantFrontController::class, 'showCategorieRestaurant'])->name('CategorieRestaurants');

// Route::get('page/restaurant/{id}', App\Http\Livewire\RestaurantFront::class)->name('restaurant');

Route::get('restaurant/password/reset', [App\Http\Controllers\RestaurantAuth\ResetPasswordController::class, 'showResetForm']);
Route::post('restaurant/password/reset', [App\Http\Controllers\RestaurantAuth\ResetPasswordController::class, 'reset']);
Route::post('restaurant/password/reset/{token}', [App\Http\Controllers\RestaurantAuth\ResetPasswordController::class, 'showResetForm']);
Route::get('restaurant/password/email', [App\Http\Controllers\RestaurantAuth\ForgotPasswordController::class, 'showLinkRequestForm']);
Route::post('restaurant/password/email', [App\Http\Controllers\RestaurantAuth\ForgotPasswordController::class, 'sendResetLinkEmail']);

Route::get('customer/password/reset', [App\Http\Controllers\CustomerAuth\ResetPasswordController::class, 'showResetForm']);
Route::post('customer/password/reset', [App\Http\Controllers\CustomerAuth\ResetPasswordController::class, 'reset']);
Route::post('customer/password/reset/{token}', [App\Http\Controllers\CustomerAuth\ResetPasswordController::class, 'showResetForm']);
Route::get('customer/password/email', [App\Http\Controllers\CustomerAuth\ForgotPasswordController::class, 'showLinkRequestForm']);
Route::post('customer/password/email', [App\Http\Controllers\CustomerAuth\ForgotPasswordController::class, 'sendResetLinkEmail']);

/*
=============================================================================================================
Back office restaurant route
=============================================================================================================
*/

Route::group(['prefix' => 'backOffice'], function () {
    Route::resource('customers', App\Http\Controllers\CustomersController::class);

    Route::resource('foodCategories', App\Http\Controllers\FoodCategoriesController::class);

    Route::resource('coupons', App\Http\Controllers\CouponController::class);

    Route::resource('otps', App\Http\Controllers\OtpsController::class);

    Route::resource('restaurants', App\Http\Controllers\RestaurantsController::class);

    Route::resource('deliveryTypes', App\Http\Controllers\DeliveryTypesController::class);

    Route::resource('vehicleTypes', App\Http\Controllers\VehicleTypesController::class);

    Route::resource('customerDevices', App\Http\Controllers\CustomerDevicesController::class);

    Route::resource('paymentMethodes', App\Http\Controllers\PaymentMethodesController::class);

    Route::resource('orders', App\Http\Controllers\OrdersController::class);

    //     Route::resource('orderDeliveries', App\Http\Controllers\OrderDeliveriesController::class);

    Route::resource('deliveries', App\Http\Controllers\DeliveryController::class);

    Route::resource('deliveryAdresses', App\Http\Controllers\DeliveryAdressesController::class);

    Route::resource('orderHistories', App\Http\Controllers\OrderHistoriesController::class);

    Route::resource('orderItems', App\Http\Controllers\OrderItemsController::class);

    Route::resource('restaurantPhones', App\Http\Controllers\RestaurantPhonesController::class);

    Route::resource('restaurantMenuses', App\Http\Controllers\RestaurantMenusController::class);

    Route::resource('foodCategories', App\Http\Controllers\FoodCategoriesController::class);

    Route::resource('restaurantCategories', App\Http\Controllers\RestaurantCategoriesController::class);

    Route::resource('restaurantUsers', App\Http\Controllers\RestaurantUsersController::class);

    Route::resource('menuses', App\Http\Controllers\MenusController::class);

    Route::resource('food', App\Http\Controllers\FoodController::class);

    Route::resource('foodParts', App\Http\Controllers\FoodPartsController::class);

    Route::resource('foodPartItems', App\Http\Controllers\FoodPartItemController::class);

    Route::resource('restaurantAvailabilities', App\Http\Controllers\RestaurantAvailabilityController::class);
});

Route::get('/login/restaurant', function () {
    return view('frontOffice.restaurant.homePage.index');
})->name('restaurantHome');

Route::get('/restaurant/congratulation', function () {
    return view('frontOffice.restaurant.pages.congratulate');
})->name('restaurantCongrate');

Route::get('/restaurant/verify/{token}', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'verifyRestaurant'])->name('verifyRestaurant');

Route::get('/restaurant/page/confirm', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'restaurantConfirmView'])->name('restaurantConfirmView');

Route::get('/restaurant/next/step/{uuid}', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'restaurantLastRegister'])->name('restaurantLastRegister');


Route::post('/restaurant/update', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'updateRestaurant'])->name('updateRestaurant');

Route::get('/restaurant/waitting', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'afterRegistrationView'])->name('afterRegistrationView');

/*
=============================================================================================================
Order and checkout route
=============================================================================================================
*/

// Order route
Route::post('/get/food/data', [App\Http\Controllers\FoodController::class, 'getFoodData'])->name('createOrder');

Route::get('/create/order', [App\Http\Controllers\OrderController::class, 'index'])->name('createOrder');

Route::post('/create/order/notAuth', [App\Http\Controllers\OrderController::class, 'notAuthIndex'])->name('createOrderNotAuth');

Route::post('/store/order', [App\Http\Controllers\OrderController::class, 'store'])->name('storeOrder');

// Payment form
Route::post('/checkout', [App\Http\Controllers\checkoutController::class, 'index'])->name('checkout');

Route::post('/changelocale', [\App\Http\Controllers\TranslationController::class, 'changeLocale'])->name('changelocale');


// Route::get('/restaurant', function () {
//     return view('frontOffice.pages.restaurantSingle');
// })->name('restaurant.show');

// Customer login page
// Route::get('/customer/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'showLoginForm'])->name('customer.login');

// Route::post('/customer/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'guard'])->name('customer.store');
// Route::get('/customer/login', function () {
//     return view('customer.Auth.login');
// })->name('login');


// Auth::routes(['verify' => true]);

Route::get('/domli-admin', [App\Http\Controllers\HomeController::class, 'index'])->middleware('verified');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware('verified');

// Route::get('/home', 'HomeController@index')->middleware('verified');


/*
============================================================================================
Customer route
============================================================================================
*/
Route::get('/partenaire/restaurants', function () {
    return view('customer.pages.pagerestau');
});


Route::get('/otp', function () {
    return view('frontOffice.pages.otpPhonePage');
})->name('otp');

Route::get('/about', function () {
    return view('frontOffice.pages.about');
})->name('aboutUs');

Route::get('/page/contact', function () {
    return view('frontOffice.pages.contact');
})->name('contactUs');

// Route::get('/order', function () {
//     return view('frontOffice.pages.orderDetail');
// })->name('orderDetail');
// /*
// ============================================================================================
// delivery route
// ============================================================================================
// */
// //

Route::get('/delivery/home', function () {
    return view('customer.homePage.test');
});

Route::get('/delivery/chooseMoveMeans', function () {
    return view('deliverer.pages.chooseMoveMeans');
})->name('chooseMoveMeans');

Route::get('/delivery/lastRegisterStep', function () {
    return view('deliverer.pages.lastRegisterStep');
})->name('lastRegister');

Route::get('/deliverer/profileAuth', function () {
    return view('deliverer.pages.profileAuth');
    // return view('frontOffice.delivery.pages.profileAuth');
})->name('profileAuth');

Route::get('/delivery/offers', function () {
    return view('deliverer.pages.offerDetail');
})->name('offers');

Route::get('/delivery/otp', function () {
    return view('deliverer.pages.otpPhonePage');
})->name('deliveryOtpPage');

app/Models/RestaurantPhones.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class RestaurantPhones
 * @package App\Models
 * @version January 8, 2021, 6:26 pm UTC
 *
 * @property integer $restaurant_id
 * @property integer $dial_code
 * @property integer $phone_number
 * @property integer $phone
 */
class RestaurantPhones extends Model
{
    use SoftDeletes;

    public $table = 'restaurant_phones';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'restaurant_id',
        'dial_code',
        'phone_number',
        'phone'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'restaurant_id' => 'integer',
        'dial_code' => 'integer',
        'phone_number' => 'integer',
        'phone' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/RestaurantPhonesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRestaurantPhonesRequest;
use App\Http\Requests\UpdateRestaurantPhonesRequest;
use App\Repositories\RestaurantPhonesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class RestaurantPhonesController extends AppBaseController
{
    /** @var  RestaurantPhonesRepository */
    private $restaurantPhonesRepository;

    public function __construct(RestaurantPhonesRepository $restaurantPhonesRepo)
    {
        $this->restaurantPhonesRepository = $restaurantPhonesRepo;
    }

    /**
     * Display a listing of the RestaurantPhones.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $restaurantPhones = $this->restaurantPhonesRepository->all();

        return view('restaurant_phones.index')
            ->with('restaurantPhones', $restaurantPhones);
    }

    /**
     * Show the form for creating a new RestaurantPhones.
     *
     * @return Response
     */
    public function create()
    {
        return view('restaurant_phones.create');
    }

    /**
     * Store a newly created RestaurantPhones in storage.
     *
     * @param CreateRestaurantPhonesRequest $request
     *
     * @return Response
     */
    public function store(CreateRestaurantPhonesRequest $request)
    {
        $input = $request->all();

        $restaurantPhones = $this->restaurantPhonesRepository->create($input);

        Flash::success('Restaurant Phones saved successfully.');

        return redirect(route('restaurantPhones.index'));
    }

    /**
     * Display the specified RestaurantPhones.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $restaurantPhones = $this->restaurantPhonesRepository->find($id);

        if (empty($restaurantPhones)) {
            Flash::error('Restaurant Phones not found');

            return redirect(route('restaurantPhones.index'));
        }

        return view('restaurant_phones.show')->with('restaurantPhones', $restaurantPhones);
    }

    /**
     * Show the form for editing the specified RestaurantPhones.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $restaurantPhones = $this->restaurantPhonesRepository->find($id);

        if (empty($restaurantPhones)) {
            Flash::error('Restaurant Phones not found');

            return redirect(route('restaurantPhones.index'));
        }

        return view('restaurant_phones.edit')->with('restaurantPhones', $restaurantPhones);
    }

    /**
     * Update the specified RestaurantPhones in storage.
     *
     * @param int $id
     * @param UpdateRestaurantPhonesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRestaurantPhonesRequest $request)
    {
        $restaurantPhones = $this->restaurantPhonesRepository->find($id);

        if (empty($restaurantPhones)) {
            Flash::error('Restaurant Phones not found');

            return redirect(route('restaurantPhones.index'));
        }

        $restaurantPhones = $this->restaurantPhonesRepository->update($request->all(), $id);

        Flash::success('Restaurant Phones updated successfully.');

        return redirect(route('restaurantPhones.index'));
    }

    /**
     * Remove the specified RestaurantPhones from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $restaurantPhones = $this->restaurantPhonesRepository->find($id);

        if (empty($restaurantPhones)) {
            Flash::error('Restaurant Phones not found');

            return redirect(route('restaurantPhones.index'));
        }

        $this->restaurantPhonesRepository->delete($id);

        Flash::success('Restaurant Phones deleted successfully.');

        return redirect(route('restaurantPhones.index'));
    }
}

resources/views/restaurant_phones/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('restaurantPhones.index') !!}">Restaurant Phones</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Restaurant Phones</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'restaurantPhones.store']) !!}

                                   @include('restaurant_phones.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/restaurant_phones/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('restaurantPhones.index') !!}">Restaurant Phones</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Restaurant Phones</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($restaurantPhones, ['route' => ['restaurantPhones.update', $restaurantPhones->id], 'method' => 'patch']) !!}

                              @include('restaurant_phones.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/restaurant_phones/fields.blade.php
<!-- Dial Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('dial_code', 'Dial Code:') !!}
    {!! Form::number('dial_code', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone_number', 'Phone Number:') !!}
    {!! Form::number('phone_number', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::number('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('restaurantPhones.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/restaurant_phones/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Restaurant Phones</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             RestaurantPhones
                             <a class="pull-right" href="{{ route('restaurantPhones.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('restaurant_phones.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/restaurant_phones/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('restaurantPhones.index') }}">Restaurant Phones</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('restaurantPhones.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('restaurant_phones.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/restaurant_phones/show_fields.blade.php
<!-- Restaurant Id Field -->
<div class="form-group">
    {!! Form::label('restaurant_id', 'Restaurant Id:') !!}
    <p>{{ $restaurantPhones->restaurant_id }}</p>
</div>

<!-- Dial Code Field -->
<div class="form-group">
    {!! Form::label('dial_code', 'Dial Code:') !!}
    <p>{{ $restaurantPhones->dial_code }}</p>
</div>

<!-- Phone Number Field -->
<div class="form-group">
    {!! Form::label('phone_number', 'Phone Number:') !!}
    <p>{{ $restaurantPhones->phone_number }}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{{ $restaurantPhones->phone }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $restaurantPhones->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $restaurantPhones->updated_at }}</p>
</div>

resources/views/restaurant_phones/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="restaurantPhones-table">
        <thead>
            <tr>
                <th>Restaurant Id</th>
        <th>Dial Code</th>
        <th>Phone Number</th>
        <th>Phone</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($restaurantPhones as $restaurantPhones)
            <tr>
                <td>{{ $restaurantPhones->restaurant_id }}</td>
            <td>{{ $restaurantPhones->dial_code }}</td>
            <td>{{ $restaurantPhones->phone_number }}</td>
            <td>{{ $restaurantPhones->phone }}</td>
                <td>
                    {!! Form::open(['route' => ['restaurantPhones.destroy', $restaurantPhones->id]]) !!}
                    @method('DELETE')
                    <div class='btn-group'>
                        <a href="{{ route('restaurantPhones.show', [$restaurantPhones->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('restaurantPhones.edit', [$restaurantPhones->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>