routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\RestaurantFrontController;
use App\Http\Controllers\CustomerFrontOfficeController;
use App\Http\Controllers\CustomerAuth\LoginController;



// Home page
Route::get('/test', function () {
    return view('customer.homePage.test');
});
Route::get('/domlii', [\App\Http\Controllers\DomliiController::class, 'index'])->name('home.index');
Route::get('/connexion', [\App\Http\Controllers\ConnexionController::class, 'index'])->name('connexion.index');
Route::get('/food-espace', [\App\Http\Controllers\FoodEspaceController::class, 'index'])->name('food_espace.index');
Route::get('/variete', [\App\Http\Controllers\VarieteController::class, 'index'])->name('variete.index');
Route::get('/', [App\Http\Controllers\HomePageController::class, 'index'])->name('homepage');
Route::get('/welcome', function () {
    return view('welcome');
});
Route::get('/accueil', [App\Http\Controllers\HomePageController::class, 'index'])->name('homepage');

Route::post('order-change_state/{order_number}', [App\Http\Controllers\OrdersController::class, 'change_status']);
/*
============================================================================================
Customer interface routes
============================================================================================
*/

Route::group(['prefix' => 'customer'], function () {
    Route::get('/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'showLoginForm'])->name('customer.login');
    Route::post('/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'login'])->name('customerLogin');

    Route::post('/logout', [App\Http\Controllers\CustomerAuth\LoginController::class, 'logout'])->name('logout');

    // Route::get('create_account/customer', [App\Http\Controllers\CustomerFrontOfficeController::class, 'showCustomerRegisterForm'])->name('customerRegisterForm');

    Route::get('/register', [App\Http\Controllers\CustomerAuth\RegisterController::class, 'showRegistrationForm'])->name('register');

    Route::post('/register', [App\Http\Controllers\CustomerAuth\RegisterController::class, 'storeCustomerAccount']);

    //->middleware('verified');

    Route::get('/home', [App\Http\Controllers\CustomerAuth\RegisterController::class, 'showHomePage'])->name('customerHome')->middleware('customer');

    Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');

    // Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');

    // Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');

    // Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');

    Route::get('/orders/{order_number}', [App\Http\Controllers\CustomerFrontOfficeController::class, 'showOrderFromOrderNumber']);
    Route::get('/profile', [App\Http\Controllers\CustomerFrontOfficeController::class, 'showProfile'])->name('profilePage');
    Route::post('/profile/update', [App\Http\Controllers\CustomerFrontOfficeController::class, 'update'])->name('profileUpdate');
    Route::get('/orders', [App\Http\Controllers\CustomerFrontOfficeController::class, 'showProfile'])->name('profilePage');

    // Route::get('/order/{id}', [App\Http\Controllers\CustomerFrontOfficeController::class, 'showProfile'])->name('showOrder');

    Route::get('/cart', [CartController::class, 'index'])->name('customerCart');

    Route::delete('/cart/distroy/{rowId}', [CartController::class, 'distroyCart'])->name('distroyCart');
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', function () {
        return redirect('/admin/login');
    });

    Route::get('/login', [App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);
    // Route::get('/register', [App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm']);
    Route::post('/login', [App\Http\Controllers\Auth\LoginController::class, 'login']);
    Route::post('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);
    // Route::post('/register', [App\Http\Controllers\Auth\RegisterController::class, 'register']);
    Route::get('/password/reset', [App\Http\Controllers\Auth\ResetPasswordController::class, 'showResetForm']);
    Route::post('/password/reset', [App\Http\Controllers\Auth\ResetPasswordController::class, 'reset']);
    Route::post('/password/reset/{token}', [App\Http\Controllers\Auth\ResetPasswordController::class, 'showResetForm']);
    Route::get('/password/email', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showLinkRequestForm']);
    Route::post('/password/email', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'sendResetLinkEmail']);

    Route::group(['middleware' => 'auth'], function () {
        Route::post('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin-home-index');
        Route::get('/foodCategories', [App\Http\Controllers\FoodCategoriesController::class, 'index'])->name('admin-foodCategories-index');
        Route::post('/foodCategories', [App\Http\Controllers\FoodCategoriesController::class, 'store'])->name('admin-foodCategories-store');
        Route::get('/foodCategories/create', [App\Http\Controllers\FoodCategoriesController::class, 'create'])->name('admin-foodCategories-create');
        Route::get('/foodCategories/{id}', [App\Http\Controllers\FoodCategoriesController::class, 'show'])->name('admin-foodCategories-show');
        Route::get('/foodCategories/{id}/edit', [App\Http\Controllers\FoodCategoriesController::class, 'edit'])->name('admin-foodCategories-edit');
        Route::put('/foodCategories/{id}', [App\Http\Controllers\FoodCategoriesController::class, 'update'])->name('admin-foodCategories-update');
        Route::delete('/foodCategories/{id}', [App\Http\Controllers\FoodCategoriesController::class, 'destroy'])->name('admin-foodCategories-delete');
        Route::get('/orders', [App\Http\Controllers\OrdersController::class, 'index'])->name('admin-orders-index');
        Route::get('/food', [App\Http\Controllers\FoodController::class, 'index'])->name('admin-food-index');
        Route::get('/foodParts', [App\Http\Controllers\FoodPartsController::class, 'index'])->name('admin-foodParts-index');
        Route::get('/customers', [App\Http\Controllers\CustomersController::class, 'index'])->name('admin-customers-index');
        Route::get('/customers/{id}', [App\Http\Controllers\CustomersController::class, 'show'])->name('admin-customers-show');
        Route::post('/customers/desable-or-enable/{id}', [App\Http\Controllers\CustomersController::class, 'change_state'])->name('admin-customers-change_state');
        Route::post('/restaurants/desable-or-enable/{id}', [App\Http\Controllers\RestaurantsController::class, 'change_state'])->name('admin-restaurants-change_state');
        Route::post('/delivery/desable-or-enable/{id}', [App\Http\Controllers\DeliveryController::class, 'change_state'])->name('admin-delivery-change_state');
        Route::post('/vehicle/desable-or-enable/{id}', [App\Http\Controllers\VehicleController::class, 'change_state'])->name('admin-vehicle-change_state');
        Route::get('/delivery/{delivery_id}/orders', [App\Http\Controllers\OrdersController::class, 'delivery'])->name('backoffice-delivery-order-index');
        Route::get('/delivery/{delivery_id}/history', [App\Http\Controllers\DeliveryPaymentHistoriqueController::class, 'delivery'])->name('backoffice-delivery-payment-history-index');
        Route::get('/delivery/{delivery_id}/request', [App\Http\Controllers\RequestDeliveryPaymentController::class, 'delivery'])->name('backoffice-delivery-payment-request-index');
        Route::get('/delivery/{delivery_id}/order_assignements', [App\Http\Controllers\OrderAssignementController::class, 'delivery'])->name('backoffice-delivery-orderassignement-index');
        Route::delete('/customers/{id}', [App\Http\Controllers\CustomersController::class, 'destroy'])->name('admin-customers-delete');
        Route::get('/customers', [App\Http\Controllers\CustomersController::class, 'index'])->name('admin-customers-index');
        Route::get('/restaurants', [App\Http\Controllers\RestaurantsController::class, 'index'])->name('admin-restaurants-index');
        Route::get('/restaurants/{id}', [App\Http\Controllers\RestaurantsController::class, 'show'])->name('admin-restaurants-show');
        Route::get('/deliverers', [App\Http\Controllers\DeliveryController::class, 'index'])->name('admin-deliverers-index');
        Route::get('/orders', [App\Http\Controllers\OrdersController::class, 'index'])->name('admin-orders-index');
        Route::get('/orders/{id}', [App\Http\Controllers\OrdersController::class, 'show'])->name('admin-orders-show');
        Route::delete('/orders/{id}', [App\Http\Controllers\OrdersController::class, 'show'])->name('admin-orders-delete');

        Route::get('/restaurant/{restaurant_id}/foods', [App\Http\Controllers\FoodController::class, 'foodsByRestaurant'])->name('admin-restaurant-food-index');
        Route::get('/restaurant/{restaurant_id}/foods/create', [App\Http\Controllers\FoodController::class, 'create'])->name('admin-restaurant-food-create');
        Route::post('/restaurant/{restaurant_id}/foods/create', [App\Http\Controllers\FoodController::class, 'store'])->name('admin-restaurant-food-store');

        Route::get('/restaurant/{restaurant_id}/category', [App\Http\Controllers\RestaurantCategoryController::class, 'categorie'])->name('admin-restaurant-categorie-index');

app/Models/Food.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Food
 * @package App\Models
 * @version January 9, 2021, 1:44 pm UTC
 *
 * @property integer $restaurant_id
 * @property integer $menu_id
 * @property integer $food_category_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property integer $price
 * @property integer $currency_code
 * @property string $currency_name
 */
class Food extends Model
{

    use SoftDeletes;

    public $table = 'food';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'restaurant_id',
        'menu_id',
        'food_category_id',
        'uuid',
        'title',
        'description',
        'image',
        'price',
        'currency_code',
        'currency_name',
        'has_part',
        'quantity'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'restaurant_id' => 'integer',
        'menu_id' => 'integer',
        'food_category_id' => 'integer',
        'uuid' => 'string',
        'title' => 'string',
        'description' => 'string',
        'image' => 'string',
        'price' => 'string',
        'currency_code' => 'integer',
        'currency_name' => 'string',
        'quantity' => 'integer',
        'has_part'  =>  'boolean',
        'created_at'    =>  'string',
        'updated_at'    =>  'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function getPrice(){
        $price = $this->price / 100;
        return '$ '.number_format($price, 2, '.', '');
    }

    public function menu(){
        return $this->belongsTo(RestaurantMenus::class, 'menu_id', 'id');
    }

    public function restaurant(){
        return $this->belongsTo(Restaurants::class, 'restaurant_id', 'id');
    }

    // public function food_category(){
    //     return $this->belongsTo(FoodCategories::class, 'food_category_id', 'id');
    // }

    public function food_category(){
        return $this->belongsTo(FoodCategories::class, 'food_category_id', 'id');
    }

    public function getPartsAttribute(){
        return  FoodParts::where(['food_id' => $this->id])->get();
    }
}

resources/views/food/create.blade.php
{{--@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('food.index') !!}">Food</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Food</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'food.store', 'files' => true]) !!}

                                   @include('food.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection
--}}

@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{!! Auth::check() ? route('admin-restaurant-food-index', ['restaurant_id' => $restaurant->uuid]) : route('backoffice-restaurant-food-index', ['restaurant_id' => $restaurant->uuid]) !!}">Food</a>
        </li>
      <li class="breadcrumb-item active">Add</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                {{-- <i class="fa fa-plus-square-o fa-lg"></i> --}}
                                <strong>{{$restaurant->title}} add food</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'food.store', 'files'=>true]) !!}

                                   @include('food.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

@push('scripts')
    <script>
        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('output_cover');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
@endpush

resources/views/food/edit.blade.php
{{--@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('food.index') !!}">Food</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Food</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($food, ['route' => ['food.update', $food->id], 'method' => 'patch', 'files' => true]) !!}

                              @include('food.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection--}}
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! Auth::check() ? route('admin-restaurant-food-index', ['restaurant_id' => $food->restaurant->uuid]) : route('backoffice-restaurant-food-index', ['restaurant_id' => $food->restaurant->uuid]) !!}">Food</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 477.873 477.873" style="enable-background:new 0 0 477.873 477.873; width: 20px;" xml:space="preserve">
                                    <path d="M392.533,238.937c-9.426,0-17.067,7.641-17.067,17.067V426.67c0,9.426-7.641,17.067-17.067,17.067H51.2 c-9.426,0-17.067-7.641-17.067-17.067V85.337c0-9.426,7.641-17.067,17.067-17.067H256c9.426,0,17.067-7.641,17.067-17.067 S265.426,34.137,256,34.137H51.2C22.923,34.137,0,57.06,0,85.337V426.67c0,28.277,22.923,51.2,51.2,51.2h307.2 c28.277,0,51.2-22.923,51.2-51.2V256.003C409.6,246.578,401.959,238.937,392.533,238.937z"/>
                                    <path d="M458.742,19.142c-12.254-12.256-28.875-19.14-46.206-19.138c-17.341-0.05-33.979,6.846-46.199,19.149L141.534,243.937 c-1.865,1.879-3.272,4.163-4.113,6.673l-34.133,102.4c-2.979,8.943,1.856,18.607,10.799,21.585 c1.735,0.578,3.552,0.873,5.38,0.875c1.832-0.003,3.653-0.297,5.393-0.87l102.4-34.133c2.515-0.84,4.8-2.254,6.673-4.13 l224.802-224.802C484.25,86.023,484.253,44.657,458.742,19.142z M434.603,87.419L212.736,309.286l-66.287,22.135l22.067-66.202 L390.468,43.353c12.202-12.178,31.967-12.158,44.145,0.044c5.817,5.829,9.095,13.72,9.12,21.955 C443.754,73.631,440.467,81.575,434.603,87.419z"/>
                                </svg>
                              <strong>Edit Food</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($food, ['route' => ['food.update', $food->id], 'method' => 'patch']) !!}

                              @include('food.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

@push('scripts')
    <script>
        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('output_cover');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
@endpush

resources/views/food/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a class="pull-right" href="{{ \Auth::check() ? url('/admin/restaurants/'.$restaurant->uuid) : url('/backOffice/restaurants/'.$restaurant->uuid) }}">Restaurant</a></li>
        <li class="breadcrumb-item">Foods</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header" style="display: flex; justify-content: space-between">
                            {{-- <i class="fa fa-align-justify"></i> --}}
                            {{$restaurant->name}} food's
                            <a class="pull-right" href="{{ \Auth::check() ? '/admin/restaurant/'.$restaurant->uuid.'/foods/create' : '/restaurant/'.$restaurant->uuid.'/foods/create' }}">
                                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve" height="28" height="28">
                                    <circle style="fill:#E8C52A;" cx="25" cy="25" r="25"/>
                                    <line style="fill:none;stroke:#FFFFFF;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;" x1="25" y1="13" x2="25" y2="38"/>
                                    <line style="fill:none;stroke:#FFFFFF;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;" x1="37.5" y1="25" x2="12.5" y2="25"/>
                                </svg>
                            </a>
                         </div>
                         <div class="card-body">
                             @include('food.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/food/show_fields.blade.php
{{--
<!-- Restaurant Id Field -->
<div class="form-group">
    {!! Form::label('restaurant_id', 'Restaurant Id:') !!}
    <p>{{ $food->restaurant_id }}</p>
</div>

<!-- Menu Id Field -->
<div class="form-group">
    {!! Form::label('menu_id', 'Menu Id:') !!}
    <p>{{ $food->menu_id }}</p>
</div>

<!-- Food Category Id Field -->
<div class="form-group">
    {!! Form::label('food_category_id', 'Food Category Id:') !!}
    <p>{{ $food->food_category_id }}</p>
</div>

<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{{ $food->title }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $food->description }}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{{ $food->image }}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', 'Price:') !!}
    <p>{{ $food->price ?? $food->base_price }}</p>
</div>

<!-- Currency Code Field -->
<div class="form-group">
    {!! Form::label('currency_code', 'Currency Code:') !!}
    <p>{{ $food->currency_code }}</p>
</div>

<!-- Currency Name Field -->
<div class="form-group">
    {!! Form::label('currency_name', 'Currency Name:') !!}
    <p>{{ $food->currency_name }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $food->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $food->updated_at }}</p>
</div>
--}}

<div class="mt-3 py-2">
    <div class="px-4">
        <div class="bg-img">
            <h1>{{ $food->title }}</h1>
        </div>
        <div class="text-center py-2">
            <small>{{ $food->description }}</small>
        </div>
        <div class="mt-3 py-2 info-container">
            <div class="row info-content">
                <div class="col-12 title">
                    <h2>Informations complémentaires</h2>
                </div>
                <div class="col-12 my-2">
                    <div class="row">
                        <div class="col-12 info-card">
                            <!-- Restaurant Id Field -->
                            <div class="form-group">
                                {!! Form::label('quantity', 'Quantity In stock:', ['class' => 'title']) !!}
                                <p>{{ $food->quantity ?? 0 }}</p>
                            </div>
                        </div>
                        @if(!is_null($food->restaurant))
                            <div class="col-12 info-card">
                                <!-- Restaurant Id Field -->
                                <div class="form-group">
                                    {!! Form::label('restaurant_id', 'Restaurant :', ['class' => 'title']) !!}
                                    <p>{{ $food->restaurant->name ?? '' }}</p>
                                </div>
                            </div>
                        @endif
                        @if(!is_null($food->menu))
                            <div class="col-12 info-card">
                                <!-- Menu Id Field -->
                                <div class="form-group">
                                    {!! Form::label('menu_id', 'Menu :', ['class' => 'title']) !!}
                                    <p>{{ $food->menu->title ?? '' }}</p>
                                </div>
                            </div>
                        @endif
                        @if(!is_null($food->category))
                            <div class="col-12 info-card">
                                <!-- Category Id Field -->
                                <div class="form-group">
                                    {!! Form::label('category_id', 'Categorie:', ['class' => 'title']) !!}
                                    <p>{{ $food->category->title ?? '' }}</p>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <div class="row info-content">
                <div class="col-lg-6 col-sm-6 lat-card">
                    <!-- Currency Code Field -->
                    <div class="form-group">
                        {!! Form::label('currency_code', 'Currency Code:', ['class' => 'title']) !!}
                        <p>{{ $food->currency_code }}</p>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6 lng-card">
                    <!-- Currency Name Field -->
                    <div class="form-group">
                        {!! Form::label('currency_name', 'Currency Name:', ['class' => 'title']) !!}
                        <p>{{ $food->currency_name }}</p>
                    </div>
                </div>
            </div>
            {{--<div class="info-content row">
                <div class="col-12 title">
                    <h2>Devise</h2>
                </div>
                <div class="col-12 my-2">
                    <div class="row">
                        <div class="col-12 info-card">
                            <!-- Currency Code Field -->
                            <div class="form-group">
                                {!! Form::label('currency_code', 'Currency Code:', ['class' => 'title']) !!}
                                <p>{{ $food->currency_code }}</p>
                            </div>
                        </div>
                        <div class="col-12 info-card">
                            <!-- Currency Name Field -->
                            <div class="form-group">
                                {!! Form::label('currency_name', 'Currency Name:', ['class' => 'title']) !!}
                                <p>{{ $food->currency_name }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>--}}
            <div class="px-4 info-content row">

                @if($food->hasPart == 1)
                    <div class="col-12 title">
                        <h2>Option(s)</h2>
                    </div>
                    <div class="col-12 mt-3">
                        @foreach($food->parts as $part)
                            <div class="col-12 info-card">
                                <div class="form-group">
                                    <p class="default">{{ $part->title }}</p>
                                </div>
                            </div>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>