routes/web.php
Route::post('/restaurant/update', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'updateRestaurant'])->name('updateRestaurant');

Route::get('/restaurant/waitting', [App\Http\Controllers\RestaurantAuth\RegisterController::class, 'afterRegistrationView'])->name('afterRegistrationView');

/*
=============================================================================================================
Order and checkout route
=============================================================================================================
*/

// Order route
Route::post('/get/food/data', [App\Http\Controllers\FoodController::class, 'getFoodData'])->name('createOrder');

Route::get('/create/order', [App\Http\Controllers\OrderController::class, 'index'])->name('createOrder');

Route::post('/create/order/notAuth', [App\Http\Controllers\OrderController::class, 'notAuthIndex'])->name('createOrderNotAuth');

Route::post('/store/order', [App\Http\Controllers\OrderController::class, 'store'])->name('storeOrder');

// Payment form
Route::post('/checkout', [App\Http\Controllers\checkoutController::class, 'index'])->name('checkout');

Route::post('/changelocale', [\App\Http\Controllers\TranslationController::class, 'changeLocale'])->name('changelocale');


// Route::get('/restaurant', function () {
//     return view('frontOffice.pages.restaurantSingle');
// })->name('restaurant.show');

// Customer login page
// Route::get('/customer/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'showLoginForm'])->name('customer.login');

// Route::post('/customer/login', [App\Http\Controllers\CustomerAuth\LoginController::class, 'guard'])->name('customer.store');
// Route::get('/customer/login', function () {
//     return view('customer.Auth.login');
// })->name('login');


// Auth::routes(['verify' => true]);

Route::get('/domli-admin', [App\Http\Controllers\HomeController::class, 'index'])->middleware('verified');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware('verified');

// Route::get('/home', 'HomeController@index')->middleware('verified');


/*
============================================================================================
Customer route
============================================================================================
*/
Route::get('/partenaire/restaurants', function () {
    return view('customer.pages.pagerestau');
});


Route::get('/otp', function () {
    return view('frontOffice.pages.otpPhonePage');
})->name('otp');

Route::get('/about', function () {
    return view('frontOffice.pages.about');
})->name('aboutUs');

Route::get('/page/contact', function () {
    return view('frontOffice.pages.contact');
})->name('contactUs');

// Route::get('/order', function () {
//     return view('frontOffice.pages.orderDetail');
// })->name('orderDetail');
// /*
// ============================================================================================
// delivery route
// ============================================================================================
// */
// //

Route::get('/delivery/home', function () {
    return view('customer.homePage.test');
});

Route::get('/delivery/chooseMoveMeans', function () {
    return view('deliverer.pages.chooseMoveMeans');
})->name('chooseMoveMeans');

Route::get('/delivery/lastRegisterStep', function () {
    return view('deliverer.pages.lastRegisterStep');
})->name('lastRegister');

Route::get('/deliverer/profileAuth', function () {
    return view('deliverer.pages.profileAuth');
    // return view('frontOffice.delivery.pages.profileAuth');
})->name('profileAuth');

Route::get('/delivery/offers', function () {
    return view('deliverer.pages.offerDetail');
})->name('offers');

Route::get('/delivery/otp', function () {
    return view('deliverer.pages.otpPhonePage');
})->name('deliveryOtpPage');

Route::get('/delivery/offer', function () {
    return view('deliverer.pages.offerDetail');
})->name('deliveryOffer');


Route::get('/customer/verify/{token}', [App\Http\Controllers\CustomerAuth\RegisterController::class, 'verifyCustomer'])->name('verifyCusomer');
Route::get('/delivery/verify/{token}', [App\Http\Controllers\DelivererAuth\RegisterController::class, 'verifyDeliverer'])->name('verifyDeliverer');

Route::get('/domli/congratulate', function () {
    return view('customer.pages.congratulate');
})->name('congratulate');


Route::get('/domli/congratulate/delivery', function () {
    return view('deliverer.pages.congratulate');
})->name('congratulateDeliverer');

// Email note verified page
// Route::get('/customer/waitpage', function () {
//     return view('customer.pages.waitpage');
// });


// Cart route

route::get('/food/detail/{uuid}', [App\Http\Controllers\CartController::class, 'foodOrderDetail'])->name('foodOrderDetail');

route::post('/add/food/', [App\Http\Controllers\CartController::class, 'store'])->name('cartStore');
route::post('/add/discount/', [App\Http\Controllers\CartController::class, 'addDiscount'])->name('addDiscount');

route::get('/cart/destroy', [App\Http\Controllers\CartController::class, 'destroy'])->name('emptyCart');

Route::group(['prefix' => 'deliverer'], function () {

    Route::get('/login', [App\Http\Controllers\DelivererAuth\LoginController::class, 'index'])->name('delivererLogin');

    Route::post('/login', [App\Http\Controllers\DelivererAuth\LoginController::class, 'login'])->name('delivery_login_post');

    Route::post('/logout', [App\Http\Controllers\DelivererAuth\LoginController::class, 'logout'])->name('delivery_logout');

    Route::get('/register', [App\Http\Controllers\DelivererAuth\RegisterController::class, 'showRegistrationForm'])->name('delivery_register_get');

    Route::post(
        '/register',
        [App\Http\Controllers\DelivererAuth\RegisterController::class, 'register']
    )->name('delivery_register_post');

    Route::post('/password/email', [App\Http\Controllers\DelivererAuth\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.request');

    Route::post('/password/reset', [App\Http\Controllers\DelivererAuth\ResetPasswordController::class, 'reset'])->name('password.email');

    Route::get('/password/reset', [App\Http\Controllers\DelivererAuth\ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.reset');

    Route::get('/password/reset/{token}', [App\Http\Controllers\DelivererAuth\ResetPasswordController::class, 'showResetForm']);
});


// OAuth Routes
Route::get('/auth/{provider}', [App\Http\Controllers\CustomerAuth\LoginController::class, 'redirectToProvider']);

Route::get('/auth/{provider}/callback', [App\Http\Controllers\CustomerAuth\LoginController::class, 'handleProviderCallback']);

Route::post('/search/restaurants', [App\Http\Controllers\RestaurantFrontController::class, 'searchRestaurant']);
Route::post('/search/foods', [App\Http\Controllers\RestaurantFrontController::class, 'searchFood']);

Route::get('policy/politic', function () {
    return view('customer.home');
});

// Route::get('/backOffice/restaurants', [App\Http\Controllers\RestaurantsController::class, 'index'])->middleware('auth');


// Route::get('/waitpage', function () {
//     return view('customer.pages.waitpage');
// })->name('wait');


Route::resource('vehicles', \App\Http\Controllers\VehicleController::class);

Route::resource('deliveryAvailaibities', \App\Http\Controllers\DeliveryAvailaibityController::class);

Route::resource('jobs', \App\Http\Controllers\JobController::class);

Route::resource('jobHistoriques', \App\Http\Controllers\JobHistoriqueController::class);

Route::resource('agentConnexions', \App\Http\Controllers\AgentConnexionController::class);

Route::resource('orderAssignements', \App\Http\Controllers\OrderAssignementController::class);

Route::resource('restaurantPayments', \App\Http\Controllers\RestaurantPaymentController::class);

Route::resource('deliveryPayments', \App\Http\Controllers\DeliveryPaymentController::class);

Route::resource('restaurantComptes', \App\Http\Controllers\RestaurantCompteController::class);

Route::resource('deliveryComptes', \App\Http\Controllers\DeliveryCompteController::class);

Route::resource('deliveryPaymentHistoriques', \App\Http\Controllers\DeliveryPaymentHistoriqueController::class);

Route::resource('restaurantPaymentHistoriques', \App\Http\Controllers\RestaurantPaymentHistoriqueController::class);
Route::get('/restaurant/{restaurant_id}/restaurantPaymentHistoriques', [\App\Http\Controllers\RestaurantPaymentHistoriqueController::class, 'restaurant'])->name('restaurantPaymentHistoriquesAdmin');

Route::resource('requestRestaurantPayments', \App\Http\Controllers\RequestRestaurantPaymentController::class);
Route::get('/restaurant/{restaurant_id}/requestRestaurantPayments', [\App\Http\Controllers\RequestRestaurantPaymentController::class, 'restaurant'])->name('requestRestaurantPaymentsAdmin');

Route::resource('requestDeliveryPayments', \App\Http\Controllers\RequestDeliveryPaymentController::class);

app/Models/AgentConnexion.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class AgentConnexion
 * @package App\Models
 * @version February 25, 2021, 12:49 pm UTC
 *
 * @property integer $deliverer_id
 * @property number $location_lat
 * @property number $location_lng
 * @property string $location_name
 * @property boolean $is_active
 */
class AgentConnexion extends Model
{
    use SoftDeletes;

    public $table = 'agent_connexions';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'deliverer_id',
        'location_lat',
        'location_lng',
        'location_name',
        'is_active'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'deliverer_id' => 'integer',
        'location_lat' => 'double',
        'location_lng' => 'double',
        'location_name' => 'string',
        'is_active' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/AgentConnexionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAgentConnexionRequest;
use App\Http\Requests\UpdateAgentConnexionRequest;
use App\Repositories\AgentConnexionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class AgentConnexionController extends AppBaseController
{
    /** @var  AgentConnexionRepository */
    private $agentConnexionRepository;

    public function __construct(AgentConnexionRepository $agentConnexionRepo)
    {
        $this->agentConnexionRepository = $agentConnexionRepo;
    }

    /**
     * Display a listing of the AgentConnexion.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $agentConnexions = $this->agentConnexionRepository->all();

        return view('agent_connexions.index')
            ->with('agentConnexions', $agentConnexions);
    }

    /**
     * Show the form for creating a new AgentConnexion.
     *
     * @return Response
     */
    public function create()
    {
        return view('agent_connexions.create');
    }

    /**
     * Store a newly created AgentConnexion in storage.
     *
     * @param CreateAgentConnexionRequest $request
     *
     * @return Response
     */
    public function store(CreateAgentConnexionRequest $request)
    {
        $input = $request->all();

        $agentConnexion = $this->agentConnexionRepository->create($input);

        Flash::success('Agent Connexion saved successfully.');

        return redirect(route('agentConnexions.index'));
    }

    /**
     * Display the specified AgentConnexion.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $agentConnexion = $this->agentConnexionRepository->find($id);

        if (empty($agentConnexion)) {
            Flash::error('Agent Connexion not found');

            return redirect(route('agentConnexions.index'));
        }

        return view('agent_connexions.show')->with('agentConnexion', $agentConnexion);
    }

    /**
     * Show the form for editing the specified AgentConnexion.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $agentConnexion = $this->agentConnexionRepository->find($id);

        if (empty($agentConnexion)) {
            Flash::error('Agent Connexion not found');

            return redirect(route('agentConnexions.index'));
        }

        return view('agent_connexions.edit')->with('agentConnexion', $agentConnexion);
    }

    /**
     * Update the specified AgentConnexion in storage.
     *
     * @param int $id
     * @param UpdateAgentConnexionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAgentConnexionRequest $request)
    {
        $agentConnexion = $this->agentConnexionRepository->find($id);

        if (empty($agentConnexion)) {
            Flash::error('Agent Connexion not found');

            return redirect(route('agentConnexions.index'));
        }

        $agentConnexion = $this->agentConnexionRepository->update($request->all(), $id);

        Flash::success('Agent Connexion updated successfully.');

        return redirect(route('agentConnexions.index'));
    }

    /**
     * Remove the specified AgentConnexion from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $agentConnexion = $this->agentConnexionRepository->find($id);

        if (empty($agentConnexion)) {
            Flash::error('Agent Connexion not found');

            return redirect()->back();
            // return redirect(route('agentConnexions.index'));
        }

        $this->agentConnexionRepository->delete($id);

        Flash::success('Agent Connexion deleted successfully.');


        return redirect()->back();
        // return redirect(route('agentConnexions.index'));
    }
}

resources/views/agent_connexions/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('agentConnexions.index') !!}">Agent Connexion</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Agent Connexion</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'agentConnexions.store']) !!}

                                   @include('agent_connexions.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/agent_connexions/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('agentConnexions.index') !!}">Agent Connexion</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Agent Connexion</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($agentConnexion, ['route' => ['agentConnexions.update', $agentConnexion->id], 'method' => 'patch']) !!}

                              @include('agent_connexions.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/agent_connexions/fields.blade.php
<!-- Location Lat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('location_lat', 'Location Lat:') !!}
    {!! Form::text('location_lat', null, ['class' => 'form-control']) !!}
</div>

<!-- Location Lng Field -->
<div class="form-group col-sm-6">
    {!! Form::label('location_lng', 'Location Lng:') !!}
    {!! Form::text('location_lng', null, ['class' => 'form-control']) !!}
</div>

<!-- Location Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('location_name', 'Location Name:') !!}
    {!! Form::text('location_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Is Active Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_active', 'Is Active:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('is_active', 0) !!}
        {!! Form::checkbox('is_active', '1', null) !!}
    </label>
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('agentConnexions.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/agent_connexions/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Agent Connexions</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             AgentConnexions
                             <a class="pull-right" href="{{ route('agentConnexions.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('agent_connexions.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/agent_connexions/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('agentConnexions.index') }}">Agent Connexion</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('agentConnexions.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('agent_connexions.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/agent_connexions/show_fields.blade.php
<!-- Deliverer Id Field -->
<div class="form-group">
    {!! Form::label('deliverer_id', 'Deliverer Id:') !!}
    <p>{{ $agentConnexion->deliverer_id }}</p>
</div>

<!-- Location Lat Field -->
<div class="form-group">
    {!! Form::label('location_lat', 'Location Lat:') !!}
    <p>{{ $agentConnexion->location_lat }}</p>
</div>

<!-- Location Lng Field -->
<div class="form-group">
    {!! Form::label('location_lng', 'Location Lng:') !!}
    <p>{{ $agentConnexion->location_lng }}</p>
</div>

<!-- Location Name Field -->
<div class="form-group">
    {!! Form::label('location_name', 'Location Name:') !!}
    <p>{{ $agentConnexion->location_name }}</p>
</div>

<!-- Is Active Field -->
<div class="form-group">
    {!! Form::label('is_active', 'Is Active:') !!}
    <p>{{ $agentConnexion->is_active }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $agentConnexion->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $agentConnexion->updated_at }}</p>
</div>

resources/views/agent_connexions/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="agentConnexions-table">
        <thead>
            <tr>
                <th>Deliverer Id</th>
        <th>Location Lat</th>
        <th>Location Lng</th>
        <th>Location Name</th>
        <th>Is Active</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($agentConnexions as $agentConnexion)
            <tr>
                <td>{{ $agentConnexion->deliverer_id }}</td>
            <td>{{ $agentConnexion->location_lat }}</td>
            <td>{{ $agentConnexion->location_lng }}</td>
            <td>{{ $agentConnexion->location_name }}</td>
            <td>{{ $agentConnexion->is_active }}</td>
                <td>
                    {!! Form::open(['route' => ['agentConnexions.destroy', $agentConnexion->id]]) !!}
                    @method('DELETE')
                    <div class='btn-group'>
                        <a href="{{ route('agentConnexions.show', [$agentConnexion->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('agentConnexions.edit', [$agentConnexion->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>